### ISSUE TITLE
Add Tipitaka Pāli Reader to Flathub

### ISSUE THREAD

**Issue by paladhammika** [bksubhuti/tipitaka-pali-reader#130]
For easy of installation through a software repository, add Tipitaka Pāli Reader to Flathub. 

The links below provide details on what is needed to publish TPR to Flathub.
https://github.com/flathub/flathub/wiki/App-Submission
https://github.com/flathub/flathub/wiki/App-Requirements

**Comment by bksubhuti** [comment]
I get confused with flathub for flutter.  However, the appImage is available from my website.
We have made a no-root install script.  I have  released it.. I will copy the sh file here for now.. and copy to my website as well.
After that, this issue will be closed.

**Comment by bksubhuti** [comment]
Would you like to join our team?  We are writing in Flutter.  it is easy to learn,but I also have nonflutter tasks to do.
Transforming and getting data ready,
Documentation, etc.   You can send an email .. same as my username to gmail.

**Comment by bksubhuti** [comment]
Please test these two files for installing appImage.. no root is required.
Make sure the appimage (from my website) and all files below are in the same directory.
https://github.com/bksubhuti/tipitaka-pali-reader/blob/master/utility/tipitaka-pali_installer.sh
https://github.com/bksubhuti/tipitaka-pali-reader/blob/master/utility/tipitaka_pali_reader.png

**Comment by paladhammika** [comment]
> Please test these two files for installing appImage.. no root is required. Make sure the appimage (from my website) and all files below are in the same directory. https://github.com/bksubhuti/tipitaka-pali-reader/blob/master/utility/tipitaka-pali_installer.sh https://github.com/bksubhuti/tipitaka-pali-reader/blob/master/utility/tipitaka_pali_reader.png

The script worked splendidly. There is just an error for the Name variable in the .desktop file 

![image](https://user-images.githubusercontent.com/93992898/206399274-f83aa851-3add-49a7-ae99-3e5c393fa16e.png)

**Comment by bksubhuti** [comment]
Thanks, It is fixed now.  I think there is not much need for snap or flatpak now that we have an install script and appimage.
The snapcraft report had like 16 or 25 users for TPP in 2 years and I'm sure more than 85% are comfortable with no-root appimage.     The only loss is the store listing, but I don't think we really lose any users due to that.
AppImages are so easy to make and snap for flutter is incredibly tedious and does not work.  I gave up.
If you want to build a flathub and have detailed instructions you ran, I might be willing to do so, but I really don't believe it is worth it.  I don't know how to make a metadata for this app.  If we have that it would be better for listing .  Furthermore, we can list on appimage hub.
 
My friend wrote the appimage no-root install script for me and there is no need for root.  
He also helped us get started with classicaltheravada.org

**Comment by bksubhuti** [comment]
closed.. for appimage

**Comment by bksubhuti** [comment]
Submitted to flathub today.  Would you like to try a pre-release?

https://www.dropbox.com/s/vhtsu3i5og63tkr/TipitakaPaliReader.flatpak?dl=0
You can install by typing

`flathub install --reinstall TipitakaPaliReader.flatpak`

**Comment by bksubhuti** [comment]
almost on flathub.. need to wait another build by them.

**Comment by bksubhuti** [comment]
Flathub is now listed on the main page with build 59.  Enjoy.  There were actually 180 installs on flathub already which is half of the Mac/ios combine.  However, I might bet it is just downloads and people who reset their system re-download the app. Let me know how it goes.  If you are able to test with a clean machine this is best.  Built with linux mint based on 22.04
