### ISSUE TITLE
DPD issue

### ISSUE THREAD

**Issue by BBBalls** [bksubhuti/tipitaka-pali-reader#146]
**Describe the bug**
The DPD search results are not always as expected.

**To Reproduce**
Unexpected behavior 1
1. Go to sidebar menu (desktop)
2. Click on dictionary icon
3. Search 'yathābhūtañāṇadassanaṃ'
4. Result entry for 'yathābhūtañāṇadassanattha'

Unexpected behavior 2 
1. Search 'yathābhūtañāṇadassana'
2. Result `yathābhūtañāṇadassana -yathābhūtañ · āṇa · dassana [ yathābhūta + āṇa + dassana ] `

Unexpected behavior 3 
1. Search 'dummaṅkūnaṃ'
2. Result entry for 'dummatī'

Unexpected behavior 4 
1. Search 'dummaṅkū'
2. Result entry for 'dummatī'

**Expected behavior**
1
The expected result is for the entry 'yathābhūtañāṇadassana'

2 
The expected result is for the entry of 'yathābhūtañāṇadassana'

3 
The expected result is the entry for 'dummaṅku'

4 
The expected result is the entry for 'dummaṅku'

**Screenshots**
1
![Screenshot from 2023-05-05 14-50-22](https://user-images.githubusercontent.com/90289469/236574880-f6bdc4b8-d852-4d0c-bb89-f4c5023ab081.png)

![Screenshot_20230505-151634_DictTango](https://user-images.githubusercontent.com/90289469/236577772-94a48b46-585f-4221-a7cb-2e78511f9542.jpg)

2
![Screenshot from 2023-05-05 14-50-59](https://user-images.githubusercontent.com/90289469/236574895-c5986b84-78d7-42f2-afd4-b6a1a5386d8a.png)

![Screenshot_20230505-151701_DictTango](https://user-images.githubusercontent.com/90289469/236577750-c39671eb-6f50-430d-994d-457eb73cf4d8.jpg)

3
![Screenshot from 2023-05-05 14-51-48](https://user-images.githubusercontent.com/90289469/236574935-5fbf3e6d-edaa-4763-b37b-cd8e9f1bc788.png)

![Screenshot_20230505-151419_DictTango](https://user-images.githubusercontent.com/90289469/236577854-449318f6-42d8-416f-afc6-22c2ae83f0e1.jpg)

4
![Screenshot from 2023-05-05 14-52-20](https://user-images.githubusercontent.com/90289469/236574954-b5ccde35-1908-4c9b-bb67-d93de0b718d8.png)

![Screenshot_20230505-151459_DictTango](https://user-images.githubusercontent.com/90289469/236577836-2503e2b3-22c8-4dc2-ae68-dd4209ff2ec4.jpg)

**Desktop (please complete the following information):**
 - OS: Linux POP!_OS 22.04
 - TPR appimage 2023-05-04 with DPD 2023-05-04 extension
 - Goldendict 1.5 Flatpak with DPD 2023-05-04 Stardict

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - up-to-date TPR 2.3.2 with DPD 2023-05-04 extension
 - DictTango 1.6.9.7 with DPD 2023-05-04 MDict

**Additional context**

**Comment by bksubhuti** [comment]
I'm still not sure what  is wrong.  The DPD is different from the dpd that gets released from month to month.  However the extensions can allow you to update the DPD dictionary without needing to wait for a new version..

Having updated with extension.. I'm still not able to find.
However, the results seem the same.. I search for dummaṅkūnaṃ and I get the same
![image](https://user-images.githubusercontent.com/18184280/236590834-81326dcb-f44c-45f4-ac3a-1572d7443c60.png)


Ironically, I had just built a new appimage with 18.04 on digital ocean.  it works on 18.04 and should work on all other ubuntu distros that come later.  There is an issue with fuse3 and fuse2 which is needed for appimage.  This is one of the faults of appimage which was thought to be infallible.  Or maybe that was the plan with the new fuse release :)
There is an idea to get a flatpak going, but it is intimidating to do and I don't have time.  However, enjoy the new appimage.
[At this link](https://drive.google.com/file/d/12uwAE9_O_8gJ_v32GKVssmv8VFrereGG/view?usp=share_link)

**Comment by BBBalls** [comment]
I was testing the newest version of the appimage with a fresh update of the DPD extension when I noticed the inconsistencies between the TPR DPD and the Golden DPD, but I don't think it is specific to the appimage, because I was able to replicate the same inconsistencies on my Android phone.

> I'm still not sure what is wrong.

Are you saying you need further clarification about what I think the problem is, or are you saying you haven't identified the cause of the issue?

>  The DPD is different from the dpd that gets released from month to month.

Are you saying TRP DPD and the Stardict DPD are at different release cadences, or that they contain different database entries?

Thanks for making an updated appimage so quickly after my request. It seems to be on par with usability / functionality as the Android build.

The usage of fuse2 for building the appimage does not seem to be in conflict with fuse3; the database generation and access seem to work as intended (at least on Ubuntu 22.04).

**Comment by bksubhuti** [comment]
The lookup methods are different and the data might be different.  Sometimes a word does not show up with type suggest especially if you paste a whole word.  If you have extra letters that are not part of the main word it will not find it in the pure dictionary lookup screen.  You can search for the word click on the word and then we remove the extra characters and find the match.  The word I mentioned was the same results with dpd using golden dict from one or two months ago   

If you paste a word, you need to slowly remove that last few letters to get a match or suggested match .

Making the appimage was coincidentally done for other reasons but built last night.  It was built for ven Bodhirasa.  It should have good compatibility since I built it on a server with 18.94.  I don't think I will package an install script .  Instead I will add links to a launch icon and a desktop file..  ven bodhirasa will be able to tell what is going on now that he has the latest release.  I will ask him to add to this issue.

**Comment by bksubhuti** [comment]
yathābhūtañāṇadassanaṃ remove last letter yathābhūtañāṇadassana will give the correct definition for yathābhūtañāṇadassana in dpd.
This is with the current code.
We do not support inflected forms with search suggest just yet. 
Why?  Because too many words would show up.  We might later.
We will close this issue.. 
If you want a feature request.. please make a simple request.

titled.. 
Dictionary Search Suggest to show inflected forms.
Use example You wish to find:  yathābhūtañāṇadassanaṃ 
but it only shows yathābhūtañāṇadassana

This issue is closed.
