### ISSUE TITLE
Have TPR check for preexisting data files before writing data files after a update.

### ISSUE THREAD

**Issue by BBBalls** [bksubhuti/tipitaka-pali-reader#167]
The extensions need to be reinstalled every time there is an update. After an update, TPR seems to assume a fresh install is occurring, and writes data files over the existing data files—erasing the installed extensions.

It will be nice if the TPR did some kind of check for the preexistence of up to date data files, so the preexisting data files are not pointlessly overwritten, and extensions do not have to be continually installed.

I do imagine overwriting is necessary when data files are updated. It will be nice if there was some kind of warning about extensions needing to be reinstalled, and if there was a clearer display as to which extension are installed.

The occurrence of overwriting data files, and disappearing extensions, happens on both the Linux version and the Android version.

**Comment by bksubhuti** [comment]
I know it is a pain, but that is the way it is for now.  There is no time savings involved except downloading.  For that reason, we can  push this for later., much later.  We do however back up the old data.  But version to version can be a problem with that as well.

Best wishes.. i guess the new linux build works :)

**Comment by BBBalls** [comment]
With the recent frequent update release cadence, is installing the DPD extension relevant or even counterproductive?

**Comment by bksubhuti** [comment]
Are you on linux?
We have done quite a few releases this month, but things will slow down.I will try to do the extension as part of the updating procedure.  I realized that it is not so difficult to know which extensions are installed because we leave the extension files in the app data folder (usually hidden from the user).  I can search for those and ask to add as part of the install.
I do hope you like the app improvements though.

**Comment by bksubhuti** [comment]
I check for residual sql files in the user directory (extensions).  Then I list (remind) the user to get the extensions again and bring them to the download screen.  Because extensions are changing based on  code and upgrades.. it is best to redownload the extensions again.  Most extensions are very small.  We also ship with recent peu and dpd  especially when building linux.

**Comment by bksubhuti** [comment]
you can test here:
https://drive.google.com/file/d/1892bvaFNoElGcaWAG4BoX-g6b3e7iMSR/view?usp=sharing
